### ISSUE TITLE
Error if node names include emoji

### ISSUE THREAD

**Issue by noon92** [pdxlocations/meshtastic-ha-entity-builder#4]
> Traceback (most recent call last):
>   File "C:\PATH\entity-builders.py", line 331, in <module>
>     file.write(config + '\n')
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f34c' in position 920: character maps to <undefined>

**Comment by pdxlocations** [comment]
Thanks for the report! May I ask what operating system you are using?  I'm pretty sure I have this working on a mac.  I don't have a node on me to test right now.

**Comment by noon92** [comment]
Hi, win10

**Comment by pdxlocations** [comment]
Thanks, I have a win11 machine at home and will try to look into this over the weekend.

**Comment by noon92** [comment]
Sounds good, thanks! I can test here when it's done.

**Comment by ianmcorvidae** [comment]
I figured out a fix for this and was talking to @noon92 on Discord about it, seems to work. I added it to my PR that adds the device trackers, because I move around where the files are being opened so it'd immediately conflict one direction or the other, easier to combine. @pdxlocations if you would prefer they be separated one direction or the other, definitely just let me know!

**Comment by noon92** [comment]
I can confirm @ianmcorvidae's fix works (not as part of the tracker PR, but just the alteration of the `with open`.
